### PR TITLE
Fix regression for callback url mismatch

### PR DESCRIPTION
**Pull request by gauravtiwari**
* Fixes regression in omniauth-oauth2 v1.4.0 by https://github.com/intridea/omniauth-oauth2/commit/85fdbe117c2a4400d001a6368cc359d88f40abc7
* Update readme

### CODE REVIEW

**Comment by lukaszkorecki** [comment]
@gauravtiwari Awesome! Thanks!

**Comment by gauravtiwari** [comment]
@lukaszkorecki Could you publish a new version to ruby gems?

**Comment by lukaszkorecki** [comment]
@gauravtiwari As per readme: you have to use git to install it. Happy to publish it to rubygems - I'll find some time to do it this weekend

**Comment by gauravtiwari** [comment]
@lukaszkorecki Yup I know :) Just thought would be good idea to publish it to ruby gems too. Yeah, no worries whenever you find time.

**Pull request merged**
